import asyncio
import json
import os
import cognee

async def main():
    print("🧠 Initializing Cognee memory for the current project...")
    
    # 1. Define the path to the Graphify output
    graphify_file = "graphify-out/graph.json" 
    
    if not os.path.exists(graphify_file):
        print(f"❌ Error: {graphify_file} not found.")
        print("Please run 'graphify .' in this directory before running this script.")
        return

    # 2. Read the structural map generated by Graphify
    with open(graphify_file, "r", encoding="utf-8") as f:
        graph_data = json.load(f)

    # 3. Ingest the data into Cognee
    print("📥 Ingesting Graphify data into Cognee...")
    await cognee.add(data=json.dumps(graph_data), dataset_name="project_codebase")
    
    # 4. Cognify! 
    print("⚙️ Processing knowledge graph (Cognifying)...")
    await cognee.cognify()
    
    print("✅ Integration complete! Claude, Codex, and Antigravity can now query this project's memory.")

if __name__ == "__main__":
    asyncio.run(main())
